apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-webapp
  namespace: {{ .Values.namespace.name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}-webapp
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
